# Homebrew formula template — kept as a manual fallback. The real formula is
# auto-generated by GoReleaser on each release and pushed to opod-io/homebrew-tap.
#
# Tap and install:
#   brew tap opod-io/tap
#   brew install opod

class Opod < Formula
  desc "Orchestrate open-weight LLMs across your machines"
  homepage "https://github.com/opod-io/opod"
  license "Apache-2.0"
  version "0.0.0" # placeholder; GoReleaser sets this

  # Optional but recommended dependency: llama.cpp ships `rpc-server` +
  # `llama-server`, which Opod launches when you `opod shard create` a
  # model across multiple machines. Single-node Opod works without it.
  # `opod doctor` warns when rpc-server is missing on the PATH.
  depends_on "llama.cpp" => :recommended

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/opod-io/opod/releases/download/v#{version}/opod-darwin-arm64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    else
      url "https://github.com/opod-io/opod/releases/download/v#{version}/opod-darwin-amd64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/opod-io/opod/releases/download/v#{version}/opod-linux-arm64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    else
      url "https://github.com/opod-io/opod/releases/download/v#{version}/opod-linux-amd64.tar.gz"
      sha256 "REPLACE_WITH_REAL_SHA256"
    end
  end

  def install
    bin.install "opod"
  end

  test do
    system "#{bin}/opod", "version"
  end
end
